### ISSUE TITLE
Feedback on execution?

### ISSUE THREAD

**Issue by olivierlacan** [shelbyd/rspec-bisect#3]
I've been running `rspec-bisect` (on RSpec 2.14.x) for approximately 5 minutes without any output. Wouldn't it be useful to display some sort of progress? 

It's hard to tell if the gem is even functioning properly.

Thanks for your work on this. :-)

**Comment by shelbyd** [comment]
It should be logging feedback to stdout.

I could imagine something along the lines of [not syncing stdout](http://blog.bigbinary.com/2009/07/04/stdout-sync-true-to-flush-output-immediately.html) could be a problem.
